server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_EMPTY_JSON_ARRAYS: true
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: always
  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true
      properties:
        org:
          hibernate:
            envers:
              audit_table_suffix: _AUDIT
              revision_field_name: REVISION_ID
              revision_type_field_name: REVISION_TYPE

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /openapi
logging:
  level:
    org.springframework.web: INFO
    #org.hibernate: debug
    #org.hibernate.type.descriptor.sql: trace
  file: logs/app.log
